// SEMUA TEKS UI — Bahasa Indonesia sehari-hari (aturan CLAUDE.md §2). Satu tempat supaya
// mudah ditinjau. Hindari jargon: "Lunas sebelum {tanggal}", bukan "sebelum saldo awal".

import type { Tone } from "@/design/tokens";

export const S = {
  app: "SANO Finance",
  tab: {
    beranda: "Beranda",
    transaksi: "Transaksi",
    persetujuan: "Persetujuan",
    laporan: "Laporan",
    lainnya: "Lainnya",
  },
  umum: {
    coba: "Coba lagi",
    batal: "Batal",
    tutup: "Tutup",
    simpan: "Simpan",
    lihatSemua: "Lihat semua",
    memuat: "Memuat…",
    cari: "Cari",
    aturUlang: "Atur ulang",
    keluar: "Keluar",
    modeContoh: "Mode contoh — data di layar ini bukan data asli",
    perTanggal: (t: string) => `Data per ${t}`,
  },
  offline: {
    banner: "Tidak ada koneksi internet",
    aksiNonaktif: "Butuh koneksi internet",
  },
  login: {
    judul: "Masuk ke SANO Finance",
    sub: "Gunakan akun SANSS Anda. Aplikasi ini untuk tim Finance.",
    email: "Email",
    sandi: "Kata sandi",
    tombol: "Masuk",
    galatKosong: "Isi email dan kata sandi dulu",
  },
  beranda: {
    totalKas: "Total kas & bank",
    rekening: "Rekening",
    aksiCepat: "Aksi cepat",
    perluTindakan: "Perlu tindakan",
    periode: "Ringkasan periode",
    labaBersih: "Laba bersih",
    piutang: "Piutang",
    utang: "Utang",
    jurnalTerakhir: "Jurnal terakhir",
    tren: "Pendapatan vs beban",
    komposisiPiutang: "Umur piutang",
    catatan: "Catatan laporan",
  },
  aksi: {
    fotoNota: "Foto nota",
    pengeluaran: "Pengeluaran",
    pembelian: "Pembelian",
    kasbon: "Kasbon",
    transfer: "Transfer kas",
    pemasukan: "Pemasukan lain",
    verifikasi: "Verifikasi pembayaran",
    refund: "Refund",
    galeri: "Impor dari galeri",
    sheetJudul: "Transaksi cepat",
    sheetSub: "Pilih yang mau dicatat. Foto nota bisa dari kamera, galeri, atau dibagikan dari WhatsApp.",
  },
  transaksi: {
    judul: "Transaksi",
    segmen: { terbukukan: "Terbukukan", pengeluaran: "Pengeluaran", pembelian: "Pembelian", kasbon: "Kasbon", pembayaran: "Pembayaran" },
    cariPlaceholder: "Cari nomor, keterangan, atau nominal",
    kosongJudul: "Tidak ada yang cocok",
    kosongIsi: "Ubah kata kunci atau atur ulang filter.",
  },
  persetujuan: {
    judul: "Persetujuan",
    kosongJudul: "Tidak ada yang menunggu",
    kosongIsi: "Semua pengajuan sudah diputuskan.",
    setujui: "Setujui",
    tolak: "Tolak",
    jenis: { expense: "Pengeluaran", purchase: "Pembelian", bill: "Tagihan supplier", refund: "Refund" } as Record<string, string>,
    semua: "Semua",
  },
  laporan: {
    judul: "Laporan keuangan",
    sub: "Angka dihitung server — sama dengan yang di web.",
    labaRugi: "Laba Rugi",
    neraca: "Neraca",
    arusKas: "Arus Kas",
    neracaSaldo: "Neraca Saldo",
    umurPiutang: "Umur Piutang",
    umurUtang: "Umur Utang",
  },
  lainnya: {
    judul: "Lainnya",
    keuangan: "Keuangan",
    akuntansi: "Akuntansi",
    pengaturan: "Pengaturan",
    kasBank: "Kas & Bank",
    piutangRefund: "Piutang & Refund",
    invoice: "Invoice & Jatuh Tempo",
    supplierUtang: "Supplier & Utang",
    jurnal: "Jurnal Umum",
    bukuBesar: "Buku Besar",
    rekonsiliasi: "Rekonsiliasi Bank",
    dataBelumLengkap: "Data Belum Lengkap",
    tinjauBukti: "Tinjau Bukti",
    keamanan: "Keamanan",
    tampilan: "Tampilan",
    perangkat: "Perangkat & sesi",
    tentang: "Tentang & bantuan",
  },
  tampilan: {
    tema: "Tema",
    sistem: "Ikuti sistem",
    terang: "Terang",
    gelap: "Gelap",
    efekRingan: "Efek ringan",
    efekRinganInfo: "Matikan blur agar lebih hemat baterai dan lancar di HP lama.",
    sembunyikan: "Sembunyikan angka",
    sembunyikanInfo: "Nominal ditampilkan sebagai titik-titik.",
  },
  segera: "Segera hadir",
  segeraIsi: "Layar ini sedang dikerjakan. Data di aplikasi selalu diambil dari server.",
} as const;

export const STATUS: Record<string, { label: string; tone: Tone }> = {
  DRAFT: { label: "Draf", tone: "neutral" },
  MENUNGGU_APPROVAL: { label: "Menunggu persetujuan", tone: "warning" },
  DISETUJUI: { label: "Disetujui", tone: "info" },
  DITOLAK: { label: "Ditolak", tone: "danger" },
  DIBAYAR: { label: "Dibayar", tone: "success" },
  DIBAYAR_SEBAGIAN: { label: "Dibayar sebagian", tone: "info" },
  LUNAS: { label: "Lunas", tone: "success" },
  DIBATALKAN: { label: "Dibatalkan", tone: "neutral" },
  AKTIF: { label: "Aktif", tone: "info" },
  POSTED: { label: "Terbukukan", tone: "success" },
  REVERSED: { label: "Dibalik", tone: "neutral" },
  BELUM_COCOK: { label: "Belum cocok", tone: "warning" },
  COCOK: { label: "Cocok", tone: "success" },
  DIABAIKAN: { label: "Diabaikan", tone: "neutral" },
  OPEN: { label: "Terbuka", tone: "success" },
  CLOSED: { label: "Terkunci", tone: "neutral" },
  BELUM_DIVERIFIKASI: { label: "Menunggu verifikasi", tone: "warning" },
  TERVERIFIKASI: { label: "Sudah diverifikasi", tone: "success" },
};

/** Status dari server → label + nada. Status yang tidak dikenal ditampilkan apa adanya (netral), tidak crash. */
export function statusInfo(status: string): { label: string; tone: Tone } {
  return STATUS[status] ?? { label: status, tone: "neutral" };
}
